// Package controller_gen provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen/v2 version v2.1.0 DO NOT EDIT.
package controller_gen

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/go-chi/chi/v5"
	"github.com/oapi-codegen/runtime"
)

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Получение истории заказов клиента
	// (GET /api/customers/{customer_id}/orders)
	GetCustomerOrderHistory(w http.ResponseWriter, r *http.Request, customerId int)
	// Список блюд и их ингредиентов
	// (GET /api/dishes/get)
	GetDishesWithIngredients(w http.ResponseWriter, r *http.Request)
	// Поиск блюд по ингредиентам
	// (GET /api/dishes/get/by-ingredients)
	GetDishesByIngredients(w http.ResponseWriter, r *http.Request)
	// Список самых популярных блюд
	// (GET /api/dishes/popular)
	GetMostPopularDishes(w http.ResponseWriter, r *http.Request)
	// Количество заказов, выполненных каждым сотрудником за период
	// (GET /api/employees/orders-count)
	GetEmployeeOrderCount(w http.ResponseWriter, r *http.Request)
	// Получение продуктов с истекающим сроком годности
	// (GET /api/products/expiring-soon)
	GetExpiringProducts(w http.ResponseWriter, r *http.Request)
	// Получение всех поставщиков для определенного продукта
	// (GET /api/products/{product_name}/suppliers)
	GetSuppliersByProduct(w http.ResponseWriter, r *http.Request, productName string)
	// Скачать отчет по финансам
	// (GET /api/report/download)
	DownloadReport(w http.ResponseWriter, r *http.Request)
}

// Unimplemented server implementation that returns http.StatusNotImplemented for each endpoint.

type Unimplemented struct{}

// Получение истории заказов клиента
// (GET /api/customers/{customer_id}/orders)
func (_ Unimplemented) GetCustomerOrderHistory(w http.ResponseWriter, r *http.Request, customerId int) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Список блюд и их ингредиентов
// (GET /api/dishes/get)
func (_ Unimplemented) GetDishesWithIngredients(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Поиск блюд по ингредиентам
// (GET /api/dishes/get/by-ingredients)
func (_ Unimplemented) GetDishesByIngredients(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Список самых популярных блюд
// (GET /api/dishes/popular)
func (_ Unimplemented) GetMostPopularDishes(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Количество заказов, выполненных каждым сотрудником за период
// (GET /api/employees/orders-count)
func (_ Unimplemented) GetEmployeeOrderCount(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Получение продуктов с истекающим сроком годности
// (GET /api/products/expiring-soon)
func (_ Unimplemented) GetExpiringProducts(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Получение всех поставщиков для определенного продукта
// (GET /api/products/{product_name}/suppliers)
func (_ Unimplemented) GetSuppliersByProduct(w http.ResponseWriter, r *http.Request, productName string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Скачать отчет по финансам
// (GET /api/report/download)
func (_ Unimplemented) DownloadReport(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// GetCustomerOrderHistory operation middleware
func (siw *ServerInterfaceWrapper) GetCustomerOrderHistory(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var err error

	// ------------- Path parameter "customer_id" -------------
	var customerId int

	err = runtime.BindStyledParameterWithOptions("simple", "customer_id", chi.URLParam(r, "customer_id"), &customerId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "customer_id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetCustomerOrderHistory(w, r, customerId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

// GetDishesWithIngredients operation middleware
func (siw *ServerInterfaceWrapper) GetDishesWithIngredients(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetDishesWithIngredients(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

// GetDishesByIngredients operation middleware
func (siw *ServerInterfaceWrapper) GetDishesByIngredients(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetDishesByIngredients(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

// GetMostPopularDishes operation middleware
func (siw *ServerInterfaceWrapper) GetMostPopularDishes(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetMostPopularDishes(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

// GetEmployeeOrderCount operation middleware
func (siw *ServerInterfaceWrapper) GetEmployeeOrderCount(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetEmployeeOrderCount(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

// GetExpiringProducts operation middleware
func (siw *ServerInterfaceWrapper) GetExpiringProducts(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetExpiringProducts(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

// GetSuppliersByProduct operation middleware
func (siw *ServerInterfaceWrapper) GetSuppliersByProduct(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var err error

	// ------------- Path parameter "product_name" -------------
	var productName string

	err = runtime.BindStyledParameterWithOptions("simple", "product_name", chi.URLParam(r, "product_name"), &productName, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "product_name", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetSuppliersByProduct(w, r, productName)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

// DownloadReport operation middleware
func (siw *ServerInterfaceWrapper) DownloadReport(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DownloadReport(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{})
}

type ChiServerOptions struct {
	BaseURL          string
	BaseRouter       chi.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r chi.Router) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r chi.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options ChiServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = chi.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/customers/{customer_id}/orders", wrapper.GetCustomerOrderHistory)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/dishes/get", wrapper.GetDishesWithIngredients)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/dishes/get/by-ingredients", wrapper.GetDishesByIngredients)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/dishes/popular", wrapper.GetMostPopularDishes)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/employees/orders-count", wrapper.GetEmployeeOrderCount)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/products/expiring-soon", wrapper.GetExpiringProducts)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/products/{product_name}/suppliers", wrapper.GetSuppliersByProduct)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/report/download", wrapper.DownloadReport)
	})

	return r
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/9xZT2/jxhX/KgS3R8mSvUEPAoKgyQbtogiySA89xAublmZlBuafHY7aCIYA/Um6DbxY",
	"X3oIAqRBLr0V4GrFLC1L9Fd4842KNzOkSHOolYysa+dkajycee/3fu8vT8225/ieS1wWmK1TM2gfE8cS",
	"j5/0AuY5hH5OO4T+yQ6YR/u47lPPJ5TZROxqq10Hdgd/dkjQprbPbM81WyZ8DzOIYMnHEPNvIIY5hHwM",
	"CR8aMIdLiNU/Q7Nmsr5PzJZpu4x0CTUHNdPDi8UlNiNOoLmbEouRzoHFNFf/S1wVGhAbMOVDiGDBzw0+",
	"ggTewgxCWELMzw14CyGKhX/NmvnMow4eZ3YsRlZSBYzabheF6tjBMVknFG7YGozXcMlfoVRaIFzLIZrz",
	"fhRST6UqEGlPWQnuU7utO+U/KBPilL1tyN8LSGAhBa5GyesdneRwcnvOkZT5ec9ymc36mht/gARtz19A",
	"xEd8DFNICrdP89dFGkQG2ZJ39BVpM3O1YFFq9TPybG2HopplSzCPWScHVVD+G17z7yAUNMMTIUYQ8Zm/",
	"3BrCdyup2/HIDo5/i5y8KWKIx19tdvzY7VLSsdMwVwlPWVG7+Gbm9SVlrjMwRaha6xtp9Knjn3h9QkRY",
	"/sTruaysEFF7KpWSofWgnb6+iYd9SqlHNUHY65AKJ58ZkPB/QgyvYQ6xlkYOCQKrqzvgZ0ggEQ4VpVxK",
	"4HX+xKhMqUHNpOR5z6akY7a+lLKtLnmq0eoJ9Tq9tg7Dr32bWijNgcgFBXtVJIc1Jhe3VNhDh/Zfer5/",
	"YhOK5FXPugzoOb7l9g8qLw7UMZVMCHJnV2U0i5GDZ9RzShjUme2QtY69ZaaokK+/BXDvipED4dPPvDLl",
	"Hjx4YPzhyWMDZnCJMXwCV3wIIUzhUnIQF4cqaSXiX0vMkfvuvgv/FWtjecCVqDdmMvbLE/g5RJhI1SIe",
	"bsDcUJXIkp/Bonx4WDNgipUSf8VfyMRSEgoiUdTwMR/yCczEEqaZBcS1a1WWWsslIlwRFdJVTlb19o6x",
	"78JPmKv5S3gLCUZ1PoYIT5TVwRs+QZWm/Azfh0tY8nOR68RBc+m0mF8uVJ6P+bmQKUTN8ZWYj/BRhXmx",
	"ZkAMS3ijEMzJXkN8Qj4SdcMYU6zcssQLShkXZVwpmmBRIdWESz7BI9KgEsOSfyMQX0DI/wEx7ktKiPBv",
	"d/ZdpK/NTpBOX5CAWT1qucz4zHKtLnGIy9D6Zs38G6GBpNTuTnOnKQKuT1zLt82W+VAs1UzfYsfCvRqW",
	"bzfSMjponOYq6kFjVQN3ia7K/Z6PlFIv4S2fwAVayHjeI7SPKoSCKwsEjA/5mXGY+fIh4iF/Mu8w4zzW",
	"AJf8JW5foRFnpIw1sF5JtCLx7wRmfLKDxBE/8eZhyzjcQMePMtE+3GvuPaw3d+vN3f1es7n3eyWlXN/d",
	"qz/cPRS2wCAlIvTjjtky/0iYtmVBqKnlECaA/PLGPcqOiYHDbAnLmWmwLzRA+ezDaI/UVD+ljV1PcXfg",
	"e24gw+xesylDusuIzMoWhua20LDxVYDSnuYOzKL17yh5huGrsWrlGqqPa2gRKUdJbGxKxEptXuyShM2L",
	"zdugZn6wpfDrZJaFhk6oHyGCOQolXH/OxyJwXkjxMC4mfCSl+eAWpPlhBQK2TJHom+BC0kmknqDnOBZ2",
	"zaYKpMXIs9atSv2x1UX6Zm15YD7FK4Rnyaa0oUKE+lPyjkdi1/Vq+DZYqKvCNyHhz3AlUkRSSBIiIn2r",
	"zxMJTO8aHYs8uJlKK/NLI2pt3zjq1691K9skjcPcu4dpltZnkjRdrHI4hBVBv1K8j1bPHzLPsZhXEdSl",
	"xh/3/x+kvTFLa3LSNBNp8RcI+XfCwHySVV6y6Iu0Nudnd5vEP21Zum3AX9/zeycWXRe/PvMC9kRuU6fc",
	"l9jFR4gCP0MXR5e54hP0Hz5ErHFRoXh/QtfGGq2xfDqlCFQFWM/GEVuFrcqSdl0E42frS96Ni1q9Er9G",
	"MasZ9NwG3zXXbkJ37VC3UNLUCp2iKIMUV3DLLzCTPXC5l01gcbcd4/3qLo4qkDHnVKm18n6lhk1BQ4yw",
	"bLdbDzwJjt6vNKWpUBRZLxDAepSP0oI1Eh3SK8xoQmaxVUn6RuS8ZdqCa2mthFKDt9sJ4umUb+t0/msB",
	"cefT+XsjQMrUzN4aop6m81HsqQeNdGgZrKsG0gFp8HE/tW6p09e06/mbNunXs8nyrbTr2qnv9qRdja6E",
	"keYqBCEvRMMpC8+r4nySv+LjcoF6cY0L97/ZLw63cx8gyNeW44vhnkj0mcqa5l734UEzZ74eaN9x6rvd",
	"cspHEKmaq2zirC1Lsgl0pMbES0jQN687dmhmzkiJ71HW6Hh/d088q3OPyrD3VII9Ukh8IYDZLk15bUZY",
	"PWCUWE6RfdkHkaO+7htSmTWf//mudwWYDV5AKL9yYwEjB/TCeMKsyPGl7BhyCUHiamSEezoYDAb/CwAA",
	"///mEKyukCIAAA==",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
