// Package controller_gen provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen/v2 version v2.1.0 DO NOT EDIT.
package controller_gen

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/go-chi/chi/v5"
	"github.com/oapi-codegen/runtime"
)

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Получение истории заказов клиента
	// (GET /api/customers/{customer_id}/orders)
	GetCustomerOrderHistory(w http.ResponseWriter, r *http.Request, customerId int)
	// Список блюд и их ингредиентов
	// (GET /api/dishes/get)
	GetDishesWithIngredients(w http.ResponseWriter, r *http.Request)
	// Поиск блюд по ингредиентам
	// (GET /api/dishes/get/by-ingredients)
	GetDishesByIngredients(w http.ResponseWriter, r *http.Request)
	// Список самых популярных блюд
	// (GET /api/dishes/popular)
	GetMostPopularDishes(w http.ResponseWriter, r *http.Request)
	// Количество заказов, выполненных каждым сотрудником за период
	// (GET /api/employees/orders-count)
	GetEmployeeOrderCount(w http.ResponseWriter, r *http.Request)
	// Получение продуктов с истекающим сроком годности
	// (GET /api/products/expiring-soon)
	GetExpiringProducts(w http.ResponseWriter, r *http.Request)
	// Получение всех поставщиков для определенного продукта
	// (GET /api/products/{product_name}/suppliers)
	GetSuppliersByProduct(w http.ResponseWriter, r *http.Request, productName string)
	// Скачать отчет по финансам
	// (GET /api/report/download)
	DownloadReport(w http.ResponseWriter, r *http.Request)
}

// Unimplemented server implementation that returns http.StatusNotImplemented for each endpoint.

type Unimplemented struct{}

// Получение истории заказов клиента
// (GET /api/customers/{customer_id}/orders)
func (_ Unimplemented) GetCustomerOrderHistory(w http.ResponseWriter, r *http.Request, customerId int) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Список блюд и их ингредиентов
// (GET /api/dishes/get)
func (_ Unimplemented) GetDishesWithIngredients(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Поиск блюд по ингредиентам
// (GET /api/dishes/get/by-ingredients)
func (_ Unimplemented) GetDishesByIngredients(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Список самых популярных блюд
// (GET /api/dishes/popular)
func (_ Unimplemented) GetMostPopularDishes(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Количество заказов, выполненных каждым сотрудником за период
// (GET /api/employees/orders-count)
func (_ Unimplemented) GetEmployeeOrderCount(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Получение продуктов с истекающим сроком годности
// (GET /api/products/expiring-soon)
func (_ Unimplemented) GetExpiringProducts(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Получение всех поставщиков для определенного продукта
// (GET /api/products/{product_name}/suppliers)
func (_ Unimplemented) GetSuppliersByProduct(w http.ResponseWriter, r *http.Request, productName string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Скачать отчет по финансам
// (GET /api/report/download)
func (_ Unimplemented) DownloadReport(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// GetCustomerOrderHistory operation middleware
func (siw *ServerInterfaceWrapper) GetCustomerOrderHistory(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var err error

	// ------------- Path parameter "customer_id" -------------
	var customerId int

	err = runtime.BindStyledParameterWithOptions("simple", "customer_id", chi.URLParam(r, "customer_id"), &customerId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "customer_id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetCustomerOrderHistory(w, r, customerId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

// GetDishesWithIngredients operation middleware
func (siw *ServerInterfaceWrapper) GetDishesWithIngredients(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetDishesWithIngredients(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

// GetDishesByIngredients operation middleware
func (siw *ServerInterfaceWrapper) GetDishesByIngredients(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetDishesByIngredients(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

// GetMostPopularDishes operation middleware
func (siw *ServerInterfaceWrapper) GetMostPopularDishes(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetMostPopularDishes(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

// GetEmployeeOrderCount operation middleware
func (siw *ServerInterfaceWrapper) GetEmployeeOrderCount(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetEmployeeOrderCount(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

// GetExpiringProducts operation middleware
func (siw *ServerInterfaceWrapper) GetExpiringProducts(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetExpiringProducts(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

// GetSuppliersByProduct operation middleware
func (siw *ServerInterfaceWrapper) GetSuppliersByProduct(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var err error

	// ------------- Path parameter "product_name" -------------
	var productName string

	err = runtime.BindStyledParameterWithOptions("simple", "product_name", chi.URLParam(r, "product_name"), &productName, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "product_name", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetSuppliersByProduct(w, r, productName)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

// DownloadReport operation middleware
func (siw *ServerInterfaceWrapper) DownloadReport(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DownloadReport(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{})
}

type ChiServerOptions struct {
	BaseURL          string
	BaseRouter       chi.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r chi.Router) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r chi.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options ChiServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = chi.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/customers/{customer_id}/orders", wrapper.GetCustomerOrderHistory)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/dishes/get", wrapper.GetDishesWithIngredients)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/dishes/get/by-ingredients", wrapper.GetDishesByIngredients)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/dishes/popular", wrapper.GetMostPopularDishes)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/employees/orders-count", wrapper.GetEmployeeOrderCount)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/products/expiring-soon", wrapper.GetExpiringProducts)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/products/{product_name}/suppliers", wrapper.GetSuppliersByProduct)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/report/download", wrapper.DownloadReport)
	})

	return r
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/9xZT2/jxhX/KgS3R9mSvUEPBoKgyRbtogiySA89xAuZlsYyA5HDHY7aCAsB+pN0G3ix",
	"vvQQBEiDXHorwNWKWVqW6K/w5hsVb2ZISeZQloxd19uTpOHwzfvzm/d+7+m53aBeQH3i89A+eG6HjVPi",
	"OfLrZ52QU4+wL1iTsD+6Iaesi+sBowFh3CVyV0PvqrtN/NkkYYO5AXepbx/Y8ANMIIa5GEIivoUEphCJ",
	"IaSib8EULiHRDyO7YvNuQOwD2/U5aRFm9yr2ictCXvcdj6Bk/TzkzPVb+LjtrHtKUWupocuJFxoUZ8Th",
	"pFl3uEHvf0o9IwsSC8aiDzHMxLklBpDCW5hABHNIxLkFbyFCm/DTrtgnlHkozm46nCxMWijVdMNTsk4p",
	"3LC1J1/DpXiFWhm9mHnomryfpNZjZQrERikLxQPmNkxS/o06oZ/yty31ewYpzJTC5V6ineP2kp/8jnes",
	"dH7WcXzu8q7hxB8hReCIFxCLgRjCGNKV08fLx8UGj/TyJXr8NWlwe7HgMOZ0c/BsHYdVM4uR4JQ77XqZ",
	"K/8Fr8X3EEmYoURI0In4Xbzc2oU3G2na8cgNT/8fMXlbj6E//uLy08d+i5Gmm+XIUvcUDXVX38xvfcGY",
	"6wgszWu51bey6Pde0KZdQmRO/4x2fF40iOg9pUa9g7xcb2RnF8UHp9QndW1FUYTRLMYoM6R42iQlKWRi",
	"QSr+AQm8hikkRpB6JAydlknAL5BCKq9rnCE1hdfLEuMiYHsVm5FnHZeRpn3wldJtcchTg1VPGG12GoYI",
	"YXmp05M6+SZwVU2+ufLoVwIlUxqywWtrYCjllGIk5A7vhBuG78+dIGi7hOFd099NBZt6geN3y6EVajHl",
	"Si3JLivA6KcTRr2Ce3a465G1eWjLwlaiX7dE/duk9J5MQSe0iOEHDx5Yv3vy2IIJXGLJGcGV6EMEY7hU",
	"oMbFvq6xqXw0x5J+6B/68B+5NlQCriQ9mqhSpSSIc4ix7utFFG7B1NLEaS7OYFYUHlUsGCMrFK/EC1UH",
	"C0pBLDmYGIq+GMFELmFVnEFSucYo9dpS3cQVSeiulnTVb+9ahz78jNRCvIS3kGIREkOIUaIiM2/ECE0a",
	"izN8Hy5hLs5laZaCpioLYDm80LQkEedSpwgtx1cSMcCvuirJNQsSmMMb7cEl3Svon0gMJM0ZIiNQW+Z4",
	"QIEgoI4LQ1PkQMpMuBQjFJFlqQTm4lvp8RlE4u+Q4L604BHx3e6hj/B1eRvh9CUJudNhjs+tzx3faRGP",
	"+Byjb1fsvxIWKkjt7dZ2azLFB8R3Atc+sB/KpYodOPxUXq+qE7jVrGUIq8+XuodedUHZW8REyn8QA23U",
	"S3grRnCBEbKedQjrogmRxMoMHSb64sw6yu/yEfpD/eT0KMc8UpZL8RK3L7yR5KBMDG69Ut6K5eMUJmK0",
	"i8CRP/Hk/oF1tIGNn+Sqfbxf23+4U9vbqe0ddmq1/d9qLdX63v7Ow70jGQtMUg564nHTPrD/QLixPUNX",
	"M8cjXDryq1v3Y7s2Jg77QEbOzurASrO3XM4465CK7h2Nuesp7g4D6ocqze7Xaiql+5woHuBgam5IC6tf",
	"h6o8LQTm2fo3jJxg+qou2taq7lmrRo8UsyRWwwKwspivNnUy5quNaq9if7Sl8ut0VszFpNRPEMMUlZJX",
	"fyqGMnFeKPUwL6ZioLT56A60+XHhBOzwYtnmwYWCkyw9YcfzHGQjtk6kq5ln7bUqzAKcFsI3H0GE9lM8",
	"Qt4s1UNXdYrQH4Xb8Ujuuk7e7wKFpqZhExD+AleyRKQrRUJmpO/MdSKF8X2D4yoObmfSIvwqiMbYV4+7",
	"O9eaq22KxtHSu0dZlTZXkqxcLGo4RCVJv1S9TxbfP+bUczgtSerK4k+7/wvQ3hqlFTUYm8iy+CtE4nsZ",
	"YDHKmZcifbEx5uLsfoP45y2p2wb4DWjQaTtsXf76nIb8idqmpXwouUsM0AviDK84XpkrMcL7I/roa1zU",
	"XvxwUtfGFq2JfDZUCTUD3MkHIFulrVJKuy6DibP1lHdjUms24l2QWcNc6i7wbjh2E7gbZ9ArlKay0ilK",
	"GqSxglt+hYnqgYu9bAqz+30x3q/tUtQKGJcuVRat5Xul51BhVc7CXL+1E1LlHPO9MlBTaSiiXnoA+agY",
	"ZIQ1lh3SK6xoUme5VWv6Rta8edaCG2GtldKTvLtJ4tnYcOty/q4cce/L+XsDQIbUPN4GoD7PRqfYU/eq",
	"2dAyXMcGsgFp+Gk3i26h0ze068snbdKv5zPaO2nXjVPf7UG7GF3JIE11CkJcyIZTEc+r1fmkeCWGRYJ6",
	"cQ0LH36zvzrcXvpHg3zjeIEc7slCn5tsaO4rN4/wDRbdJPXmazkWA4g15yqGOG/L0nwCHesx8RxSvJvX",
	"L3Zk55eRkYAyXm3Sv/lt6jQ/IBr2nijYI+2JL6VjtitTtMEJ3wk5I463ir78D5HjrunvpSJqvvjTfe8K",
	"sBq8gEj9KY8ERg3oZfBkWBHjc9UxLBUE5VcrB9zTXq/X+28AAAD//5WMUxd8IwAA",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
